### PR TITLE
[WIP] Adding parametrizations for 2D functions

### PR DESCRIPTION
**Pull request by simonepeirone**
Implementing 
-abstract parametrization
-constant parametrization
-linear parametrization 
for 2D functions.

### CODE REVIEW

**Comment by EFTCAMB** [comment]
Add your name to the !> @author list in all files so that it appears in the automatic documentation. Since you developed these files put it as first.

**Comment by EFTCAMB** [comment]
Let's use camel cases for the names of the procedures. Like:

```
ParametrizedFunction2DFirstDerivativex => ParametrizedFunction2DFirstDerivativeX
```

so that it's easier to read.

**Comment by EFTCAMB** [comment]
In the abstract implementation the two function variables are called scale factors. Perhaps it is better to call them first and second variables! We can also maintain consistency with the description in the type. I.e.:

```
!< function that returns the second partial derivative of the function with respect to x.
!<Function that returns the value of the second partial derivative of the function
!! with respect to the first scale factor.
```

This should (hopefully) show up better in the automatic documentation.
After this fix the abstract file works!

**Comment by EFTCAMB** [comment]
Also the constant implementation works.

**Comment by EFTCAMB** [comment]
Did you check wether the code compiles?

**Comment by simonepeirone** [comment]
Ok there was one mistake. Now it compiles properly.

**Comment by EFTCAMB** [comment]
Great! Will fully check the PR later! Can you rebase to update the changes that have been going on?
In particular this will allow Travis CI to test your pull request!
To rebase commit all changes and then:

```
git pull --rebase upstream/new_features
```

while on your local new_feature branch (and upstream is the remote with the EFTCAMB/EFTCAMB code)

**Comment by EFTCAMB** [comment]
Hi Simone, checking the PR! My comments:
- Remove the files with the tilde at the end;
- Remove modifications to the Travis file;
- In file eftcamb/04p0_neutral_parametrizations_2D.f90 the modules EFTDef and AMLutils are not needed;
- Use the same structure of ConstantParametrized2DInitFromFile in BilinearParametrized2DInitFromFile

After this can be merged.

**Pull request merged**
